<?php
/*
Template Name: Migrate
*/
?>
<?php nocache_headers() ?>

<form method="get" action="/migrate/">

	<label for="id">Migrate: </label><?php wp_dropdown_categories( array( 'taxonomy' => 'program', 'name' => 'id' ) ); ?>
	<input type="submit" value="Start">

</form>

<ul>

<?php

	if( isset( $_GET['id'] ) ){


		$wp_posts = array(
  array('ID' => '1220','post_author' => '1','post_date' => '2011-02-07 15:27:00','post_date_gmt' => '2011-02-07 15:27:00','post_content' => 'City Academy hosts this edition of Behind the Minds. See how this school is changing inner-city education in St. Louis. Plus, find out how hot cocoa is helping children learn halfway around the world, hear how a young composer is sharing his musical masterpieces with the world and how a local organization is keeping the sound of music alive in area schools. And, don&#039;t miss our Mystery St. Louisan. See if you can guess her identity before the end of the show. Here&#039;s a hint: she attended John Burroughs High School but now she and her sister live and work in Hollywood.','post_title' => 'February 2011','post_excerpt' => '','post_status' => 'publish','comment_status' => 'open','ping_status' => 'open','post_password' => '','post_name' => 'february-2011','to_ping' => '','pinged' => '','post_modified' => '2011-02-07 15:27:00','post_modified_gmt' => '2011-02-07 15:27:00','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/february-2011/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '1261','post_author' => '1','post_date' => '2010-10-21 09:59:00','post_date_gmt' => '2010-10-21 09:59:00','post_content' => 'We&#039;re coming to you in this edition of Behind the Minds from what used to be a school.  Find out what interesting new use the building has and why many ornate buildings like it, designated by the famous St. Louis architect, William Ittner, are now deserted and in disrepair. Also, we&#039;ll introduce you to an Extraordinary Educator who&#039;s students are singing his praises. Find out why students fondly call this teacher, "crazy." In this episode&#039;s It Takes a Village report, you&#039;ll see how an organization is training local students to be "trouble makes of the best kind." And, find out how a Standout Student took a science fair project and turned it into a successful after school program. All of that, plus see if you can guess our Mystery St. Louisan. Here&#039;s a hint: this celebrity attended McCluer High School.  ','post_title' => 'November 2010','post_excerpt' => '','post_status' => 'publish','comment_status' => 'closed','ping_status' => 'closed','post_password' => '','post_name' => 'november-2010','to_ping' => '','pinged' => '','post_modified' => '2014-05-29 12:26:34','post_modified_gmt' => '2014-05-29 17:26:34','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/november-2010/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '1263','post_author' => '1','post_date' => '2010-08-21 10:17:00','post_date_gmt' => '2010-08-21 10:17:00','post_content' => 'Thomas Mapother attended school at the site of this edition of Behind the Minds, Fern Ridge High School.  Don&#039;t know who Thomas Mapother is?  Watch to find out what name the star now goes by.  We&#039;ll also explain the complicated process teachers go through to assign students to teachers for the school year, and how a program is helping teen Moms and Dads be great parents and students.  Plus, meet Simone Bernstein, a teen who designed a popular website that earned her a national award and, a young rapper who got his start in the music business through a class assignment.','post_title' => 'August 2010','post_excerpt' => '','post_status' => 'publish','comment_status' => 'closed','ping_status' => 'closed','post_password' => '','post_name' => 'august-2010','to_ping' => '','pinged' => '','post_modified' => '2014-05-29 11:20:11','post_modified_gmt' => '2014-05-29 16:20:11','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/august-2010/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '1265','post_author' => '1','post_date' => '2010-03-21 10:30:00','post_date_gmt' => '2010-03-21 10:30:00','post_content' => 'This edition of Behind the Minds is packed with ideas of things to do in St. Louis this summer. We join you from the St. Louis Zoo with stories on programs ranging from Magic Camp to Construction Camp.','post_title' => 'May 2010','post_excerpt' => '','post_status' => 'publish','comment_status' => 'closed','ping_status' => 'closed','post_password' => '','post_name' => 'may-2010','to_ping' => '','pinged' => '','post_modified' => '2014-05-29 10:58:09','post_modified_gmt' => '2014-05-29 15:58:09','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/may-2010/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '1267','post_author' => '1','post_date' => '2010-02-21 10:42:00','post_date_gmt' => '2010-02-21 10:42:00','post_content' => 'This edition of Behind the Minds will look like it&#039;s coming to you from a professional television studio, but we&#039;re actually surrounded by McCluer North high school students in their video department. See their impressive set-up from which they produce hours of original programming each week, plus these stories: local elementary students are honoring our World War II veterans in a unique way. Find out how they&#039;re showing their appreciation at 32,000 feet. While hip hop dancing might be popular with some teens and tweens, it&#039;s ballroom dancing that has kids spinning around the room in some local schools. We&#039;ll show you how it&#039;s not just dance moves they&#039;re picking up. And, she&#039;s bound to become students&#039; new best friend, we&#039;ll introduce you to a former teacher who&#039;s advocating for less homework. We&#039;ll explain why she says her plan will better educate kids.
','post_title' => 'February 2010','post_excerpt' => '','post_status' => 'publish','comment_status' => 'closed','ping_status' => 'closed','post_password' => '','post_name' => 'february-2010','to_ping' => '','pinged' => '','post_modified' => '2014-05-29 10:55:50','post_modified_gmt' => '2014-05-29 15:55:50','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/february-2010/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '1269','post_author' => '1','post_date' => '2009-11-21 10:58:00','post_date_gmt' => '2009-11-21 10:58:00','post_content' => 'The St. Louis Chess Club and Scholastic Center in the Central West End hosted this edition of Behind the Minds.  See how chess has joined the everyday lineup of classes at some St. Louis schools and how it&#039;s teaching elementary students more than just academic lessons.  We&#039;ll also give you some inside tips on how to catch judges&#039; attention at upcoming science fairs and introduce you to some interesting ways local teachers are getting their students jazzed about all areas of science.  Where do students turn to when they need to talk?  Behind the Minds shows you a special call-in center manned by teens.  We learn about a unique program called Beauty & Bias where students explore how cultural bias shapes definitions of beauty. Learn about these stories and much more on Behind the Minds.
','post_title' => 'November 2009','post_excerpt' => '','post_status' => 'publish','comment_status' => 'closed','ping_status' => 'closed','post_password' => '','post_name' => 'november-2009','to_ping' => '','pinged' => '','post_modified' => '2014-05-29 10:51:24','post_modified_gmt' => '2014-05-29 15:51:24','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/november-2009/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '1277','post_author' => '1','post_date' => '2009-08-23 09:26:00','post_date_gmt' => '2009-08-23 09:26:00','post_content' => 'This edition of Behind the Minds comes to you from the newly renovated Magic House in Kirkwood. We show you how the $15 million expansion includes an effort to excite children about civics lessons. You&#039;ll also see an in-depth story on an innovative program in the Maplewood Richmond Heights School District that&#039;s helping homeless students stay in school. Homelessness is growing at such a rapid rate, that many schools around the nation are now taking note of the program&#039;s success. Speaking of success, Westminster Christian Academy has had a lot of it in a special competition. You&#039;ll be impressed by the team&#039;s skills and ten-year winning streak! Plus, find out why students in the Ladue school district are saying, "Yes We Can!" See why a Mehlville school district teacher&#039;s goal is to make math count with her students. And, don&#039;t miss how the Riverview Gardens school district is growing their test scores with an outdoor classroom and how some students are using a special online service to land a job!','post_title' => 'August 2009','post_excerpt' => '','post_status' => 'publish','comment_status' => 'closed','ping_status' => 'closed','post_password' => '','post_name' => 'august-2009','to_ping' => '','pinged' => '','post_modified' => '2014-05-29 13:55:48','post_modified_gmt' => '2014-05-29 18:55:48','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/august-2009/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '1279','post_author' => '1','post_date' => '2009-03-23 10:03:00','post_date_gmt' => '2009-03-23 10:03:00','post_content' => 'In this edition of Behind the Minds, we talk with local experts and school administrators about how to handle the bullying problem. We also visit with a group of Parkway students who witnessed history unfold as the 44th President of the United States was sworn into office. One local student adopts a cause and starts an anti-smoking campaign that is rallying peers to help spread the word to younger students about the dangers of tobacco. A group of Lindbergh teachers pull out the etiquette book to mentor young girls and teach them all about manners. Students from all across our area participate in the Character Plus Peace Ball Celebration to promote peace through positive reinforcement and art. Parkway students get to be producers, directors and editors of their own films in their very own film festival and physical education teachers in the Rockwood district are nationally recognized for the program they&#039;ve developed to promote health and wellness received national attention.','post_title' => 'March 2009','post_excerpt' => '','post_status' => 'publish','comment_status' => 'open','ping_status' => 'open','post_password' => '','post_name' => 'march-2009','to_ping' => '','pinged' => '','post_modified' => '2009-03-23 10:03:00','post_modified_gmt' => '2009-03-23 10:03:00','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/march-2009/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '1281','post_author' => '1','post_date' => '2008-11-23 10:13:00','post_date_gmt' => '2008-11-23 10:13:00','post_content' => 'On this edition of Behind the Minds, we take a look into how schools are handling the ever-growing population of students with autism. Another tragic problem prevalent among Missouri teens is suicide. The Rockwood district is leading the nation with a new suicide prevention program. We&#039;ll also show you an innovative program called Mad Science that has students getting into science and loving it and HEC-TV Live! offers students across the nation the opportunity to interact live with authors, historians, artists, and other experts. Two German artists make their way to St. Louis and help students make unique art pieces with the use of light, changing their understanding of art and the world.','post_title' => 'November 2008','post_excerpt' => '','post_status' => 'publish','comment_status' => 'closed','ping_status' => 'closed','post_password' => '','post_name' => 'november-2008','to_ping' => '','pinged' => '','post_modified' => '2014-05-29 10:13:01','post_modified_gmt' => '2014-05-29 15:13:01','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/november-2008/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '1283','post_author' => '1','post_date' => '2008-05-23 10:22:00','post_date_gmt' => '2008-05-23 10:22:00','post_content' => 'On this edition of Behind the Minds, Truman Elementary students are learning everything from math to genealogy to poetry from a local cemetery, while the Pattonville district is proud of one of their alums who gets his name in the history books for his work in space. Catholic Schools Performing Arts night gives students a chance to grace the stage of the Fox Theatre and show off their art and talent. Finally, in the Ladue School District, we see parents getting help on the job from a parent coach.','post_title' => 'May 2008','post_excerpt' => '','post_status' => 'publish','comment_status' => 'closed','ping_status' => 'closed','post_password' => '','post_name' => 'may-2008','to_ping' => '','pinged' => '','post_modified' => '2014-05-29 09:48:53','post_modified_gmt' => '2014-05-29 14:48:53','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/may-2008/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '1285','post_author' => '1','post_date' => '2008-02-23 10:28:00','post_date_gmt' => '2008-02-23 10:28:00','post_content' => 'On this edition of Behind the Minds, 5th graders get a taste of the real world for a day at Biz Town thanks to a unique program designed by Junior Achievement. Students in the Rockwood District dig up the past as they learn about archeology, and the Pattonville District rises to the challenge to combat childhood obesity, getting their students moving and motivated. The Cappies for local students are about equivalent to the professional Emmy award. This high school level award is changing the lives of local young people. And another student changes lives through music as she takes what she loves into children&#039;s hospitals across the nation. We also hear from a successful graduate of Cor Jesu.','post_title' => 'February 2008','post_excerpt' => '','post_status' => 'publish','comment_status' => 'closed','ping_status' => 'closed','post_password' => '','post_name' => 'february-2008','to_ping' => '','pinged' => '','post_modified' => '2014-05-29 09:44:55','post_modified_gmt' => '2014-05-29 14:44:55','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/february-2008/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '1287','post_author' => '1','post_date' => '2007-10-23 10:35:00','post_date_gmt' => '2007-10-23 10:35:00','post_content' => 'On this edition of Behind the Minds, see how the Bayless School District handles diversity in the classroom, the Gateway Institute of Technology shows off its Aviation program, and you&#039;ll learn how careers in the medical field are being encouraged in the Hazelwood District. In the Ferguson-Florissant School District, students are taking full advantage of the A+ program to earn free college credit hours, and we visit the St. Louis Poetry Center and take a look at how they are reaching out and drawing young people in to the art of poetry.','post_title' => 'October 2007','post_excerpt' => '','post_status' => 'publish','comment_status' => 'closed','ping_status' => 'closed','post_password' => '','post_name' => 'october-2007','to_ping' => '','pinged' => '','post_modified' => '2014-05-29 09:36:47','post_modified_gmt' => '2014-05-29 14:36:47','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/october-2007/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '2138','post_author' => '1','post_date' => '2011-06-11 09:20:00','post_date_gmt' => '2011-06-11 09:20:00','post_content' => 'Behind the Minds traveled to St. Justin Martyr School in Sunset Hills for this episode of the show.  Find out what a teacher at that school is doing to catch the eye of national awards committees.  Plus, everybody takes spelling tests, right?  Not in St. Louis.  We&#039;ll tell you which two school districts have done away with the exams and they&#039;re reasoning behind the decision.  Also, learn how senior citizens are filling in where budget cuts left educational holes.  And, prepare to be impressed by a group of students making movies while they&#039;re still in elementary school!  All of that, plus see if you can guess our Mystery St. Louisan: his job requires him to be light on his feet and to spend a lot of hours in the gym.','post_title' => 'May 2011','post_excerpt' => '','post_status' => 'publish','comment_status' => 'closed','ping_status' => 'closed','post_password' => '','post_name' => 'may-2011-3','to_ping' => '','pinged' => '','post_modified' => '2014-06-05 13:31:04','post_modified_gmt' => '2014-06-05 18:31:04','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/may-2011-3/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '2312','post_author' => '1','post_date' => '2011-07-18 14:10:00','post_date_gmt' => '2011-07-18 14:10:00','post_content' => 'Go Flyers! ','post_title' => 'August 2011','post_excerpt' => '','post_status' => 'publish','comment_status' => 'open','ping_status' => 'open','post_password' => '','post_name' => 'august-2011','to_ping' => '','pinged' => '','post_modified' => '2011-07-18 14:10:00','post_modified_gmt' => '2011-07-18 14:10:00','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/august-2011/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '2630','post_author' => '1','post_date' => '2011-08-18 10:29:00','post_date_gmt' => '2011-08-18 10:29:00','post_content' => 'This segment won in the Historical/Cultural - Program Story/Feature category. Congratulations to producer Gina Kurre and editor Greg Kopp. Some local students are not only learning about the Greatest Generation, they&#039;re helping to give them the ride of their lives. Watch this special story that takes you on a trip from St. Louis to Washington D.C. and back. This was a segment in Behind the Minds - February 2010.','post_title' => 'Honor Flight','post_excerpt' => '','post_status' => 'publish','comment_status' => 'closed','ping_status' => 'closed','post_password' => '','post_name' => 'honor-flight','to_ping' => '','pinged' => '','post_modified' => '2014-06-05 14:52:13','post_modified_gmt' => '2014-06-05 19:52:13','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/honor-flight/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '2632','post_author' => '1','post_date' => '2011-08-18 10:30:00','post_date_gmt' => '2011-08-18 10:30:00','post_content' => 'This segment won in the Education/Schools category. Congratulations to producer Angie Weidinger and editor Jayne Ballew. Maplewood Richmond Heights School District&#039;s innovative Joe&#039;s Place program provides hope and a place to call their own to homeless youths. This was a segment in Behind the Minds - August 2009.','post_title' => 'Joe\'s Place','post_excerpt' => '','post_status' => 'publish','comment_status' => 'closed','ping_status' => 'closed','post_password' => '','post_name' => 'joes-place-2','to_ping' => '','pinged' => '','post_modified' => '2014-06-05 14:52:53','post_modified_gmt' => '2014-06-05 19:52:53','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/joes-place-2/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '2662','post_author' => '1','post_date' => '2011-08-24 09:49:00','post_date_gmt' => '2011-08-24 09:49:00','post_content' => 'See how Katlyn Sansone used her talents to help others in our community.','post_title' => 'August 2011: Picture Perfect','post_excerpt' => '','post_status' => 'publish','comment_status' => 'open','ping_status' => 'open','post_password' => '','post_name' => 'august-2011-picture-perfect','to_ping' => '','pinged' => '','post_modified' => '2011-08-24 09:49:00','post_modified_gmt' => '2011-08-24 09:49:00','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/august-2011-picture-perfect/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '2813','post_author' => '1','post_date' => '2011-11-14 14:04:00','post_date_gmt' => '2011-11-14 14:04:00','post_content' => 'We&#039;re in the Wentzville school district for this edition of Behind the Minds where some Timberland High School students got our hosts&#039; toes tapping. ','post_title' => 'November 2011','post_excerpt' => '','post_status' => 'publish','comment_status' => 'open','ping_status' => 'open','post_password' => '','post_name' => 'november-2011-2','to_ping' => '','pinged' => '','post_modified' => '2011-11-14 14:04:00','post_modified_gmt' => '2011-11-14 14:04:00','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/november-2011-2/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '3062','post_author' => '1','post_date' => '2012-02-23 15:42:00','post_date_gmt' => '2012-02-23 15:42:00','post_content' => 'A local student&#039;s life is changed by American Idol, the clock&#039;s ticking to enroll students in summer camps &ndash; especially those that rock, People magazine features a St. Louis judge for changing students&#039; lives, a historical program disappears thanks to budget cuts and Roosevelt High School is touting their successes and victories on this edition of Behind the Minds from Mehlville High School.','post_title' => 'February 2012','post_excerpt' => '','post_status' => 'publish','comment_status' => 'open','ping_status' => 'open','post_password' => '','post_name' => 'february-2012-2','to_ping' => '','pinged' => '','post_modified' => '2013-02-01 06:00:27','post_modified_gmt' => '2013-02-01 06:00:27','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/february-2012-2/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '3283','post_author' => '1','post_date' => '2012-05-20 12:38:00','post_date_gmt' => '2012-05-20 12:38:00','post_content' => 'This episode of Behind the Minds literally begins on a high note from Crossroads College Preparatory School&#039;s "Harmonic Rush."  The a cappella group formed less than a year ago is already impressing crowds with their incredible harmonies.  You&#039;ll also meet a "Standout Student" from the school who&#039;s becoming a role model for others.  Behind the Minds strives to feature innovative academic programs and inspiring educators and students from around the St. Louis area and this episode is no exception with features on College Bound, the Parkway Digital Film Festival, Hazelwood West High School and more.  Co-host Gina Kurre also reports on how area schools are addressing the growing problem of heroin addiction and overdoes among high school students. ','post_title' => 'May 2012','post_excerpt' => '','post_status' => 'publish','comment_status' => 'open','ping_status' => 'open','post_password' => '','post_name' => 'may-2012-2','to_ping' => '','pinged' => '','post_modified' => '2012-05-20 12:38:00','post_modified_gmt' => '2012-05-20 12:38:00','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/may-2012-2/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '3452','post_author' => '1','post_date' => '2012-08-16 13:05:00','post_date_gmt' => '2012-08-16 13:05:00','post_content' => 'Join hosts Gina Kurre and Jerry Bryan at Hazelwood West Middle School where they&#039;ll discuss several education issues affecting our area schools including: the significance of MAP test scores and a unique way some Jennings teachers motivated their students to study hard for them, the prevalence of teachers pursuing and attaining post-secondary education, and the importance of community outreach in bringing unique artistic opportunities to local schools.  That, plus meet a couple of incredible Hazelwood West alums; one who just graduated from the middle school and is already a CEO of his own company and another who is proud to teach at her alma mater school district (along with a number of other alum teachers).  That plus see if you can guess where our mystery St. Louisan went to high school.','post_title' => 'August 2012','post_excerpt' => '','post_status' => 'publish','comment_status' => 'open','ping_status' => 'open','post_password' => '','post_name' => 'august-2012-2','to_ping' => '','pinged' => '','post_modified' => '2012-08-16 13:05:00','post_modified_gmt' => '2012-08-16 13:05:00','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/august-2012-2/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '3635','post_author' => '1','post_date' => '2012-10-12 14:30:00','post_date_gmt' => '2012-10-12 14:30:00','post_content' => 'There&#039;s a lot more to education than blackboards and textbooks. Behind the Minds takes you behind the school doors to highlight educational initiatives within St. Louis city and county K-12 schools. Watch for teachers, staff, administrators, and students who will blow your mind with innovative ideas and programs.','post_title' => 'November 2012','post_excerpt' => '','post_status' => 'private','comment_status' => 'open','ping_status' => 'open','post_password' => '','post_name' => 'november-2012','to_ping' => '','pinged' => '','post_modified' => '2012-10-12 14:30:00','post_modified_gmt' => '2012-10-12 14:30:00','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/november-2012/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '3783','post_author' => '1','post_date' => '2013-01-26 10:54:00','post_date_gmt' => '2013-01-26 10:54:00','post_content' => 'Behind the Minds is the only show in St. Louis focusing solely on education, and the students, parents and teachers finding solutions to challenges in our schools.  In this episode, we explore the infamous St. Louis question, "Where did you go to high school?"  Could choosing between a public or private high school affect your future opportunities and income?  A Federal Reserve economist weighs in, and a panel of six college bound high school seniors offers advice for parents and middle schoolers about how to make this tough decision.  We&#039;ll also show you around Ritenour High School&#039;s new fine arts facility.  The multi-million dollar auditorium is professional grade.  At a time when many schools in the area are cutting arts budgets, find out why this school district is investing in them.  You&#039;ll also meet the founder of a popular website who&#039;s also published a book, and he&#039;s only in middle school!  Hear his inspiring success story, and the advice his father offers for other parents on encouraging children to excel.  Finally, studies are now showing you can get a lot more than just that warm and fuzzy feeling from philanthropy.  Learn about the health benefits of giving to others. ','post_title' => 'February 2013','post_excerpt' => '','post_status' => 'publish','comment_status' => 'open','ping_status' => 'open','post_password' => '','post_name' => 'february-2013-3','to_ping' => '','pinged' => '','post_modified' => '2013-02-15 20:18:01','post_modified_gmt' => '2013-02-15 20:18:01','post_content_filtered' => '','post_parent' => '0','guid' => 'http://hectv.wpengine.com/video/february-2013-3/','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '11515','post_author' => '10','post_date' => '2013-05-23 15:33:53','post_date_gmt' => '2013-05-23 20:33:53','post_content' => '','post_title' => 'Cleveland Military Academy Students Fight for Their School, May 2013','post_excerpt' => '','post_status' => 'publish','comment_status' => 'open','ping_status' => 'open','post_password' => '','post_name' => 'may-2013','to_ping' => '','pinged' => '','post_modified' => '2013-05-24 15:06:58','post_modified_gmt' => '2013-05-24 20:06:58','post_content_filtered' => '','post_parent' => '0','guid' => 'http://www.hectv.org/?post_type=video&#038;p=11515','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '12671','post_author' => '10','post_date' => '2013-08-21 13:01:02','post_date_gmt' => '2013-08-21 18:01:02','post_content' => '','post_title' => 'Missouri\'s Education Crisis, September 2013','post_excerpt' => '','post_status' => 'publish','comment_status' => 'open','ping_status' => 'open','post_password' => '','post_name' => 'september-2013-2','to_ping' => '','pinged' => '','post_modified' => '2013-09-30 13:10:40','post_modified_gmt' => '2013-09-30 18:10:40','post_content_filtered' => '','post_parent' => '0','guid' => 'http://www.hectv.org/?post_type=video&#038;p=12671','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '13439','post_author' => '10','post_date' => '2013-12-18 07:00:24','post_date_gmt' => '2013-12-18 13:00:24','post_content' => '','post_title' => 'ADHD - A Major Childhood Health Issue, December 2013','post_excerpt' => '','post_status' => 'publish','comment_status' => 'closed','ping_status' => 'closed','post_password' => '','post_name' => 'december-2013','to_ping' => '','pinged' => '','post_modified' => '2013-12-30 13:37:53','post_modified_gmt' => '2013-12-30 19:37:53','post_content_filtered' => '','post_parent' => '0','guid' => 'http://www.hectv.org/?post_type=video&#038;p=13439','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '14205','post_author' => '10','post_date' => '2014-03-19 08:14:20','post_date_gmt' => '2014-03-19 13:14:20','post_content' => '','post_title' => 'Flipping the Classroom, March 2014','post_excerpt' => '','post_status' => 'publish','comment_status' => 'closed','ping_status' => 'closed','post_password' => '','post_name' => 'march-2014-2','to_ping' => '','pinged' => '','post_modified' => '2014-04-01 09:25:53','post_modified_gmt' => '2014-04-01 14:25:53','post_content_filtered' => '','post_parent' => '0','guid' => 'http://www.hectv.org/?post_type=video&#038;p=14205','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '15014','post_author' => '10','post_date' => '2014-06-18 07:12:37','post_date_gmt' => '2014-06-18 12:12:37','post_content' => '','post_title' => 'School\'s Out for the Summer, June 2014','post_excerpt' => '','post_status' => 'publish','comment_status' => 'closed','ping_status' => 'closed','post_password' => '','post_name' => 'june-2014','to_ping' => '','pinged' => '','post_modified' => '2014-06-23 12:05:09','post_modified_gmt' => '2014-06-23 17:05:09','post_content_filtered' => '','post_parent' => '0','guid' => 'http://www.hectv.org/?post_type=video&#038;p=15014','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '15019','post_author' => '6','post_date' => '2014-05-23 07:26:21','post_date_gmt' => '2014-05-23 12:26:21','post_content' => '','post_title' => 'Jackie Robinson\'s Breaking Barriers Essay Contest, May 2014','post_excerpt' => '','post_status' => 'publish','comment_status' => 'closed','ping_status' => 'closed','post_password' => '','post_name' => 'jackie-robinsons-breaking-barriers-essay-contest-may-2014','to_ping' => '','pinged' => '','post_modified' => '2014-05-30 10:14:51','post_modified_gmt' => '2014-05-30 15:14:51','post_content_filtered' => '','post_parent' => '0','guid' => 'http://www.hectv.org/?post_type=video&#038;p=15019','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '15088','post_author' => '6','post_date' => '2014-06-03 13:16:25','post_date_gmt' => '2014-06-03 18:16:25','post_content' => '','post_title' => 'Top of Her Game, May 2014','post_excerpt' => '','post_status' => 'publish','comment_status' => 'closed','ping_status' => 'closed','post_password' => '','post_name' => 'top-of-her-game-may-2014','to_ping' => '','pinged' => '','post_modified' => '2014-06-05 13:53:18','post_modified_gmt' => '2014-06-05 18:53:18','post_content_filtered' => '','post_parent' => '0','guid' => 'http://www.hectv.org/?post_type=video&#038;p=15088','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '15508','post_author' => '10','post_date' => '2014-09-18 15:03:55','post_date_gmt' => '2014-09-18 20:03:55','post_content' => '','post_title' => 'Common Core Confusion, September 2014','post_excerpt' => '','post_status' => 'publish','comment_status' => 'closed','ping_status' => 'closed','post_password' => '','post_name' => 'september-2014-2','to_ping' => '','pinged' => '','post_modified' => '2014-09-19 10:27:20','post_modified_gmt' => '2014-09-19 15:27:20','post_content_filtered' => '','post_parent' => '0','guid' => 'http://www.hectv.org/?post_type=video&#038;p=15508','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '15789','post_author' => '6','post_date' => '2014-09-09 11:15:31','post_date_gmt' => '2014-09-09 16:15:31','post_content' => '','post_title' => 'Boats of Opportunity, September 2014','post_excerpt' => '','post_status' => 'publish','comment_status' => 'closed','ping_status' => 'closed','post_password' => '','post_name' => 'boats-of-opportunity-september-2014','to_ping' => '','pinged' => '','post_modified' => '2014-09-09 11:15:31','post_modified_gmt' => '2014-09-09 16:15:31','post_content_filtered' => '','post_parent' => '0','guid' => 'http://www.hectv.org/?post_type=video&#038;p=15789','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0'),
  array('ID' => '16284','post_author' => '10','post_date' => '2014-12-10 09:49:24','post_date_gmt' => '2014-12-10 15:49:24','post_content' => '','post_title' => 'Education Topics from The Soulard School, December 2014','post_excerpt' => '','post_status' => 'publish','comment_status' => 'closed','ping_status' => 'closed','post_password' => '','post_name' => 'december-2014','to_ping' => '','pinged' => '','post_modified' => '2014-12-17 08:59:18','post_modified_gmt' => '2014-12-17 14:59:18','post_content_filtered' => '','post_parent' => '0','guid' => 'http://www.hectv.org/?post_type=video&#038;p=16284','menu_order' => '0','post_type' => 'video','post_mime_type' => '','comment_count' => '0')
);

	foreach( $wp_posts as $wp_post ){



		wp_insert_post( $wp_post );

	}


	}

?>

<ul>